### ISSUE TITLE
Cassandra does not starting

### ISSUE THREAD

**Issue by plebanip** [DITAS-Project/tub-dummy-example#2]
Tried to run the example but I failed. 

Execute with: docker-compose -f docker-compose.demo.yml up --build

after several minutes (even hours) the log returns

kibana_1           | {"type":"log","@timestamp":"2018-02-15T10:14:27Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"No living connections"}
vdc_1              | wait for cassandra

**Comment by tawalaya** [comment]
Looks to be a system memory issue, we recomend using at least 6 GB to start all containers on OSX and Windows.
